/** Trigramas: 3 líneas de abajo hacia arriba; 1 = yang (línea entera), 0 = yin (línea partida). */
export type Trigrama = "cielo" | "tierra" | "trueno" | "agua" | "montana" | "viento" | "fuego" | "lago";

export interface Hexagrama {
  numero: number;          // 1..64 (orden del Rey Wen)
  nombre: string;          // nombre en español, p.ej. "Lo Creativo"
  chino: string;           // caracteres, p.ej. "乾"
  pinyin: string;          // p.ej. "Qián"
  lineas: [0|1,0|1,0|1,0|1,0|1,0|1]; // de abajo (índice 0) hacia arriba (índice 5); 1 = yang, 0 = yin
  trigramaInferior: Trigrama;
  trigramaSuperior: Trigrama;
  palabrasClave: string[];   // 3-4
  juicio: string;            // 1-2 oraciones: esencia del Juicio (Dictamen), reformulado en español claro, no copia literal de Wilhelm
  imagen: string;            // 1-2 oraciones: la Imagen y su consejo para la persona
  significado: string;       // 2-3 oraciones: qué significa recibir este hexagrama hoy, en segunda persona
  amor: string;              // 1 oración
  trabajo: string;           // 1 oración
}

/** Líneas de cada trigrama, de abajo hacia arriba. */
export const TRIGRAMAS: Record<Trigrama, [0|1,0|1,0|1]> = {
  cielo: [1, 1, 1],
  tierra: [0, 0, 0],
  trueno: [1, 0, 0],
  agua: [0, 1, 0],
  montana: [0, 0, 1],
  viento: [0, 1, 1],
  fuego: [1, 0, 1],
  lago: [1, 1, 0],
};

export const HEXAGRAMAS: Hexagrama[] = [
  {
    numero: 1,
    nombre: "Lo Creativo",
    chino: "乾",
    pinyin: "Qián",
    lineas: [1, 1, 1, 1, 1, 1],
    trigramaInferior: "cielo",
    trigramaSuperior: "cielo",
    palabrasClave: ["fuerza", "iniciativa", "claridad", "perseverancia"],
    juicio: "La energía creadora está en su punto más alto y promete un gran éxito a quien actúe con rectitud. La constancia es lo que convierte ese impulso en logros duraderos.",
    imagen: "El cielo se mueve sin pausa y sin cansancio. Fortalécete de la misma manera: con disciplina diaria y sin depender de la aprobación ajena.",
    significado: "Recibes una fuente de energía pura, lista para dar forma a lo que te propongas. Es momento de tomar la iniciativa con serenidad, sin arrogancia ni prisa. Lo que empieces ahora con intención clara tendrá bases firmes.",
    amor: "Tu presencia es fuerte y atractiva; ofrece firmeza sin intentar dominar a la otra persona.",
    trabajo: "Lidera con visión y constancia; los proyectos que impulses ahora tienen viento a favor.",
  },
  {
    numero: 2,
    nombre: "Lo Receptivo",
    chino: "坤",
    pinyin: "Kūn",
    lineas: [0, 0, 0, 0, 0, 0],
    trigramaInferior: "tierra",
    trigramaSuperior: "tierra",
    palabrasClave: ["receptividad", "entrega", "paciencia", "sostén"],
    juicio: "El éxito llega cuando se acompaña en lugar de dirigir, con la constancia tranquila de la tierra. Buscar amistades y aliados en el camino trae bendición.",
    imagen: "La tierra sostiene y nutre todo lo que crece sobre ella. Sé amplio de carácter y da espacio a los demás sin perder tu propio centro.",
    significado: "Hoy no toca empujar, sino recibir y sostener lo que ya está en marcha. Tu fortaleza está en la paciencia y en la capacidad de adaptarte al terreno. Deja que la situación madure y responde con dedicación cuando te necesiten.",
    amor: "Escuchar y acompañar vale más que cualquier gesto grandilocuente; la ternura constante construye vínculo.",
    trabajo: "Apoya el proyecto de otros con generosidad; tu aporte silencioso será el que dé estabilidad al equipo.",
  },
  {
    numero: 3,
    nombre: "La Dificultad Inicial",
    chino: "屯",
    pinyin: "Zhūn",
    lineas: [1, 0, 0, 0, 1, 0],
    trigramaInferior: "trueno",
    trigramaSuperior: "agua",
    palabrasClave: ["comienzo", "caos", "germinación", "ayuda"],
    juicio: "Todo comienzo es confuso y lleno de obstáculos, pero encierra un gran potencial si se persevera. No conviene avanzar solo; busca colaboradores que sostengan el esfuerzo.",
    imagen: "Nubes y trueno anuncian la tormenta que precede al orden. Como quien desenreda hilos, organiza con paciencia lo que hoy parece un enredo.",
    significado: "Estás en el arranque de algo nuevo y la sensación de desorden es normal. No interpretes las trabas como señal de fracaso, sino como el esfuerzo del brote por atravesar la tierra. Pide ayuda, ordena prioridades y no fuerces el ritmo.",
    amor: "Una relación que empieza necesita tiempo y paciencia; no exijas claridad antes de que haya confianza.",
    trabajo: "Un proyecto recién iniciado tropieza con lo imprevisto; delega, planifica y no intentes resolverlo todo de una vez.",
  },
  {
    numero: 4,
    nombre: "La Necedad Juvenil",
    chino: "蒙",
    pinyin: "Méng",
    lineas: [0, 1, 0, 0, 0, 1],
    trigramaInferior: "agua",
    trigramaSuperior: "montana",
    palabrasClave: ["aprendizaje", "inexperiencia", "guía", "humildad"],
    juicio: "La inexperiencia no es un defecto si se reconoce y se busca enseñanza con sinceridad. Quien pregunta una y otra vez sin escuchar la respuesta pierde la guía del maestro.",
    imagen: "Un manantial brota al pie de la montaña y va abriéndose camino. Actúa con la misma decisión: aprende paso a paso y cultiva tu carácter mientras avanzas.",
    significado: "Hay algo que aún no sabes y hoy conviene admitirlo. Acércate a quien tenga más experiencia con actitud abierta, sin insistir en que te repitan lo mismo. La humildad de aprender te ahorrará errores innecesarios.",
    amor: "Reconoce lo que no entiendes de la otra persona y pregunta con curiosidad en vez de suponer.",
    trabajo: "Es momento de formarte o pedir consejo; no finjas dominar lo que apenas estás conociendo.",
  },
  {
    numero: 5,
    nombre: "La Espera",
    chino: "需",
    pinyin: "Xū",
    lineas: [1, 1, 1, 0, 1, 0],
    trigramaInferior: "cielo",
    trigramaSuperior: "agua",
    palabrasClave: ["espera", "confianza", "nutrición", "momento oportuno"],
    juicio: "Si esperas con sinceridad y confianza, la claridad llegará y el resultado será favorable. La perseverancia trae fortuna, y aun cruzar grandes aguas resulta posible cuando el momento es el adecuado.",
    imagen: "Las nubes suben al cielo y la lluvia aún no cae. Mientras tanto, come, descansa y mantén el buen ánimo: la espera también se cultiva.",
    significado: "Lo que deseas está en camino, pero todavía no es tiempo de actuar. Forzar la situación solo desgastaría tu energía; la mejor estrategia es prepararte con calma. Confía en que las condiciones cambiarán y estarás listo cuando ocurra.",
    amor: "No presiones ni exijas respuestas inmediatas; deja que el sentimiento madure a su propio ritmo.",
    trabajo: "Una decisión o respuesta importante se demora; usa ese tiempo para afinar tu propuesta y descansar.",
  },
  {
    numero: 6,
    nombre: "El Conflicto",
    chino: "訟",
    pinyin: "Sòng",
    lineas: [0, 1, 0, 1, 1, 1],
    trigramaInferior: "agua",
    trigramaSuperior: "cielo",
    palabrasClave: ["disputa", "prudencia", "mediación", "detenerse"],
    juicio: "Aunque tengas razón, la disputa se enreda si insistes hasta el final. Conviene detenerse a mitad de camino, buscar a alguien imparcial y no emprender grandes movimientos.",
    imagen: "El cielo sube y el agua baja: sus caminos se separan. Antes de iniciar cualquier cosa, piensa bien el comienzo para no sembrar conflictos futuros.",
    significado: "Estás dentro de una tensión o discusión en la que las posiciones se alejan cada vez más. Ganar a toda costa te dejaría peor que un acuerdo a medias. Busca un mediador, cede en lo que no es esencial y no abras nuevos frentes.",
    amor: "Una discusión repetida no se resuelve teniendo razón; baja el tono y busca lo que ambos comparten.",
    trabajo: "Evita escalar un desacuerdo laboral; recurre a una tercera persona neutral y aclara los términos desde el principio.",
  },
  {
    numero: 7,
    nombre: "El Ejército",
    chino: "師",
    pinyin: "Shī",
    lineas: [0, 1, 0, 0, 0, 0],
    trigramaInferior: "agua",
    trigramaSuperior: "tierra",
    palabrasClave: ["disciplina", "liderazgo", "organización", "causa justa"],
    juicio: "Una empresa colectiva prospera cuando la dirige alguien experimentado y con integridad, y cuando la causa es justa. Así no hay culpa y sí buena fortuna.",
    imagen: "Bajo la tierra se acumula el agua, como la fuerza del pueblo que un buen líder cuida. Sé generoso con quienes dependen de ti y ganarás su lealtad.",
    significado: "Te enfrentas a una tarea que requiere orden, estrategia y gente coordinada. La autoridad se gana con el ejemplo y con una meta que valga la pena. Organiza tus recursos, define roles y actúa con firmeza y humanidad.",
    amor: "La relación necesita acuerdos claros y responsabilidad compartida, no imposiciones.",
    trabajo: "Asume el liderazgo con disciplina y cuida a tu equipo; una causa clara une esfuerzos dispersos.",
  },
  {
    numero: 8,
    nombre: "La Solidaridad",
    chino: "比",
    pinyin: "Bǐ",
    lineas: [0, 0, 0, 0, 1, 0],
    trigramaInferior: "tierra",
    trigramaSuperior: "agua",
    palabrasClave: ["unión", "pertenencia", "lealtad", "centro"],
    juicio: "La unión trae fortuna cuando gira en torno a un centro firme y confiable. Quien llega tarde a esa unión, después de dudar, queda fuera.",
    imagen: "El agua sobre la tierra fluye y se junta en los lugares bajos. Como los antiguos reyes, establece lazos de confianza con quienes te rodean.",
    significado: "Es tiempo de decidir a quién perteneces y con quién caminas. Pregúntate si eres un punto de apoyo confiable para los demás o si estás postergando tu compromiso. Sumarte con sinceridad a una comunidad, ahora y no después, es lo que te fortalece.",
    amor: "El vínculo pide compromiso sincero; la indecisión prolongada aleja a la otra persona.",
    trabajo: "Únete con claridad al equipo o proyecto que valores; la colaboración sostenida da resultados.",
  },
  {
    numero: 9,
    nombre: "La Fuerza Domesticadora de lo Pequeño",
    chino: "小畜",
    pinyin: "Xiǎo Chù",
    lineas: [1, 1, 1, 0, 1, 1],
    trigramaInferior: "cielo",
    trigramaSuperior: "viento",
    palabrasClave: ["contención", "detalles", "suavidad", "preparación"],
    juicio: "Hay éxito, pero limitado: las nubes se acumulan sin que caiga la lluvia. Solo se puede influir con delicadeza y en asuntos pequeños.",
    imagen: "El viento recorre el cielo y frena las nubes sin poder retenerlas. Pule tu apariencia y tus modos; lo grande aún no está a tu alcance.",
    significado: "Tu fuerza está momentáneamente contenida por circunstancias que no puedes controlar. No es fracaso, sino una pausa que te permite ocuparte de los detalles y de tu preparación. Persuade con suavidad y espera la lluvia con paciencia.",
    amor: "Los gestos pequeños y la amabilidad cotidiana logran más que las grandes declaraciones.",
    trabajo: "Avanza en tareas menores y perfecciona lo que ya tienes; una decisión grande todavía no madura.",
  },
  {
    numero: 10,
    nombre: "El Porte",
    chino: "履",
    pinyin: "Lǚ",
    lineas: [1, 1, 0, 1, 1, 1],
    trigramaInferior: "lago",
    trigramaSuperior: "cielo",
    palabrasClave: ["conducta", "cautela", "cortesía", "tacto"],
    juicio: "Se camina sobre la cola del tigre y este no muerde: la conducta correcta permite atravesar peligros. Con buenas maneras y sinceridad hay éxito.",
    imagen: "El cielo arriba y el lago abajo marcan la diferencia natural entre lo alto y lo bajo. Distingue con claridad los lugares y roles, y actúa con el trato que corresponde a cada uno.",
    significado: "Te mueves en una situación delicada, cerca de alguien poderoso o de un tema sensible. Tu cortesía y tu tacto son la mejor protección; la torpeza podría despertar al tigre. Pisa con cuidado, sin adular ni provocar.",
    amor: "El respeto y la delicadeza en el trato evitan que una diferencia se convierta en herida.",
    trabajo: "Trata con cuidado a superiores o clientes exigentes; el buen modo abre puertas que la brusquedad cierra.",
  },
  {
    numero: 11,
    nombre: "La Paz",
    chino: "泰",
    pinyin: "Tài",
    lineas: [1, 1, 1, 0, 0, 0],
    trigramaInferior: "cielo",
    trigramaSuperior: "tierra",
    palabrasClave: ["armonía", "prosperidad", "florecimiento", "unión"],
    juicio: "Lo pequeño se va y lo grande llega: es tiempo de fortuna y éxito. Cielo y tierra se unen, y todo lo que vive florece.",
    imagen: "Cielo y tierra se entrelazan. Como quien reparte los frutos de esa unión, ordena y comparte lo bueno que llega para que alcance a todos.",
    significado: "Entras en un período de armonía en el que las cosas encajan casi sin esfuerzo. Aprovecha esta corriente favorable para consolidar, repartir y agradecer, sabiendo que ningún ciclo dura para siempre. Mantén la humildad en la abundancia.",
    amor: "La relación fluye con entendimiento mutuo; disfruta y cuida esa cercanía sin darla por sentada.",
    trabajo: "Las circunstancias te favorecen; concreta acuerdos y distribuye bien los beneficios del buen momento.",
  },
  {
    numero: 12,
    nombre: "El Estancamiento",
    chino: "否",
    pinyin: "Pǐ",
    lineas: [0, 0, 0, 1, 1, 1],
    trigramaInferior: "tierra",
    trigramaSuperior: "cielo",
    palabrasClave: ["bloqueo", "retirada", "integridad", "espera"],
    juicio: "Los caminos están cerrados y la gente mezquina prospera; a la persona íntegra no le conviene actuar. Lo grande se va y lo pequeño llega.",
    imagen: "Cielo y tierra se separan y no se comunican. Protege tu integridad retirándote a lo esencial y no aceptes honores que exigen doblegarte.",
    significado: "Hoy las cosas no fluyen, y no es por falta de mérito tuyo, sino porque el ambiente está trabado. Insistir sería desgastarte contra una puerta cerrada. Resguarda tus valores, reduce tu exposición y espera a que el ciclo gire.",
    amor: "La incomunicación domina; no fuerces conversaciones ahora, cuida tu paz interior y espera un mejor momento.",
    trabajo: "El entorno laboral está bloqueado; no comprometas tus principios por avanzar y mantén perfil bajo.",
  },
  {
    numero: 13,
    nombre: "La Comunidad con los Hombres",
    chino: "同人",
    pinyin: "Tóng Rén",
    lineas: [1, 0, 1, 1, 1, 1],
    trigramaInferior: "fuego",
    trigramaSuperior: "cielo",
    palabrasClave: ["comunidad", "apertura", "objetivo común", "claridad"],
    juicio: "La comunidad que se construye a la luz del día, con fines abiertos, tiene éxito y permite emprender grandes cosas. La perseverancia de una persona íntegra la sostiene.",
    imagen: "El fuego asciende hacia el cielo, con el que comparte naturaleza. Organiza a las personas según lo que las une, respetando lo que las diferencia.",
    significado: "Es momento de salir de lo privado y unirte a otros en torno a una meta compartida. La alianza funciona si es transparente y no por camarillas ni intereses ocultos. Tu claridad de propósito atraerá a quienes piensan parecido.",
    amor: "Compartir amistades, proyectos e ideales fortalece el vínculo más que el aislamiento en pareja.",
    trabajo: "Colabora abiertamente y busca objetivos comunes; las alianzas transparentes prosperan.",
  },
  {
    numero: 14,
    nombre: "La Posesión de lo Grande",
    chino: "大有",
    pinyin: "Dà Yǒu",
    lineas: [1, 1, 1, 1, 0, 1],
    trigramaInferior: "cielo",
    trigramaSuperior: "fuego",
    palabrasClave: ["abundancia", "claridad", "generosidad", "responsabilidad"],
    juicio: "Gran posesión y gran éxito: una línea suave en el lugar de honor recibe la respuesta de todos los fuertes. La riqueza se conserva con modestia y claridad.",
    imagen: "El fuego brilla en lo alto del cielo e ilumina todo. Frena lo dañino, favorece lo bueno y obedece a lo que sabes correcto.",
    significado: "Tienes más de lo que crees: recursos, apoyo, talento o buena reputación. La cuestión no es acumular, sino administrar esa abundancia con lucidez y sin soberbia. Comparte la luz y evita que el exceso se convierta en descuido.",
    amor: "Hay riqueza afectiva a tu alcance; recíbela con gratitud y sin posesividad.",
    trabajo: "Gozas de reconocimiento y recursos; úsalos con transparencia y generosidad para que perduren.",
  },
  {
    numero: 15,
    nombre: "La Modestia",
    chino: "謙",
    pinyin: "Qiān",
    lineas: [0, 0, 1, 0, 0, 0],
    trigramaInferior: "montana",
    trigramaSuperior: "tierra",
    palabrasClave: ["humildad", "equilibrio", "sencillez", "perseverancia"],
    juicio: "La modestia conduce al éxito y la persona íntegra la lleva hasta el final. Lo que está lleno se vacía y lo humilde se llena.",
    imagen: "Una montaña escondida dentro de la tierra. Reduce lo que sobra, aumenta lo que falta y pesa las cosas con equilibrio.",
    significado: "No necesitas demostrar nada: tu valor habla por sí mismo cuando no lo exhibes. Hoy la sencillez te abre más puertas que la insistencia en tu mérito. Nivela lo que esté desbalanceado en tu vida y actúa sin ruido.",
    amor: "La humildad de reconocer errores y escuchar sin defensa acerca más que cualquier orgullo.",
    trabajo: "Deja que tu trabajo hable; ceder el protagonismo te gana respeto y confianza duraderos.",
  },
  {
    numero: 16,
    nombre: "El Entusiasmo",
    chino: "豫",
    pinyin: "Yù",
    lineas: [0, 0, 0, 1, 0, 0],
    trigramaInferior: "tierra",
    trigramaSuperior: "trueno",
    palabrasClave: ["entusiasmo", "movimiento", "inspiración", "preparación"],
    juicio: "Es favorable nombrar ayudantes y poner ejércitos en marcha: el entusiasmo que sigue al momento adecuado moviliza a todos sin esfuerzo.",
    imagen: "El trueno brota de la tierra con fuerza y alegría. Como los antiguos hacían música para honrar lo sagrado, celebra y comparte lo que te inspira.",
    significado: "Una energía contagiosa te empuja a moverte y a mover a otros. Aprovéchala para iniciar, convocar y celebrar, pero cuida que no se convierta en euforia sin dirección. El entusiasmo genuino sigue el ritmo natural de las cosas, no lo fuerza.",
    amor: "La alegría compartida enciende el vínculo; invita a la otra persona a algo que ambos disfruten.",
    trabajo: "Tu ánimo puede motivar al equipo; canaliza esa energía en un plan concreto y con aliados claros.",
  },
  {
    numero: 17,
    nombre: "El Seguimiento",
    chino: "隨",
    pinyin: "Suí",
    lineas: [1, 0, 0, 1, 1, 0],
    trigramaInferior: "trueno",
    trigramaSuperior: "lago",
    palabrasClave: ["adaptación", "seguir", "flexibilidad", "confianza"],
    juicio: "Seguir con rectitud y perseverancia trae gran éxito. Solo quien se adapta al tiempo y a las personas correctas logra que otros lo sigan también.",
    imagen: "El trueno descansa en el fondo del lago cuando llega el otoño. Al anochecer, retírate a descansar: hay tiempos para actuar y tiempos para seguir el ritmo.",
    significado: "Hoy no se trata de imponer tu camino, sino de reconocer a quién o a qué vale la pena seguir. Adaptarte con sinceridad no es debilidad, siempre que no traiciones tus valores. Fluye con la corriente y descansa cuando el cuerpo lo pide.",
    amor: "Acompaña el ritmo de la otra persona sin perderte; la flexibilidad genuina fortalece la confianza.",
    trabajo: "Sigue una buena dirección o mentor con lealtad; adaptarte a las circunstancias te llevará lejos.",
  },
  {
    numero: 18,
    nombre: "El Trabajo en lo Echado a Perder",
    chino: "蠱",
    pinyin: "Gǔ",
    lineas: [0, 1, 1, 0, 0, 1],
    trigramaInferior: "viento",
    trigramaSuperior: "montana",
    palabrasClave: ["reparación", "corrupción", "herencia", "renovación"],
    juicio: "Reparar lo que se ha echado a perder trae gran éxito y permite emprender lo difícil. Reflexiona tres días antes de empezar y tres días después de terminar.",
    imagen: "El viento sopla al pie de la montaña y agita lo que estaba estancado. Despierta a las personas y fortalece su ánimo para restaurar lo dañado.",
    significado: "Hay algo descuidado, heredado o corrompido que hoy te toca arreglar. No es culpa tuya, pero sí es tu responsabilidad, y esa tarea puede traer una renovación profunda. Analiza las causas antes de actuar y revisa los efectos después.",
    amor: "Viejos malentendidos o patrones heredados de la familia piden ser sanados con paciencia y honestidad.",
    trabajo: "Te toca poner orden en un desastre que otros dejaron; hazlo con método y sin reproches.",
  },
  {
    numero: 19,
    nombre: "El Acercamiento",
    chino: "臨",
    pinyin: "Lín",
    lineas: [1, 1, 0, 0, 0, 0],
    trigramaInferior: "lago",
    trigramaSuperior: "tierra",
    palabrasClave: ["acercamiento", "crecimiento", "primavera", "aprovechar"],
    juicio: "El acercamiento trae gran éxito y conviene perseverar, pero al llegar el octavo mes vendrá la desgracia: aprovecha el tiempo favorable mientras dura.",
    imagen: "La tierra se alza sobre el lago y lo abraza. Enseña sin cansarte y cuida a las personas sin poner límites a tu generosidad.",
    significado: "Algo bueno se acerca a ti y tú te acercas a algo bueno; la energía crece como en primavera. Es tiempo de involucrarte, enseñar, guiar y aprovechar el impulso. Ten presente que este ciclo de expansión no es eterno.",
    amor: "Un acercamiento afectivo se da con naturalidad; recíbelo con calidez y sin miedo.",
    trabajo: "Aprovecha el crecimiento actual para acercarte a tu equipo y a nuevas oportunidades antes de que el ciclo cambie.",
  },
  {
    numero: 20,
    nombre: "La Contemplación",
    chino: "觀",
    pinyin: "Guān",
    lineas: [0, 0, 0, 0, 1, 1],
    trigramaInferior: "tierra",
    trigramaSuperior: "viento",
    palabrasClave: ["observación", "perspectiva", "ejemplo", "recogimiento"],
    juicio: "Como en el instante de recogimiento antes de la ofrenda, la contemplación seria y sincera inspira confianza en quienes miran hacia arriba.",
    imagen: "El viento recorre la tierra y toca cada rincón. Como los antiguos reyes que visitaban las regiones, observa a las personas y enseña con el ejemplo.",
    significado: "Es un día para mirar antes de actuar: tomar distancia, entender el panorama y observarte a ti mismo. Tu actitud es vista por otros y tiene un efecto que no siempre notas. Cultiva una presencia serena y coherente.",
    amor: "Observa con atención lo que la otra persona muestra y calla; comprender precede a cualquier decisión.",
    trabajo: "Analiza la situación completa antes de moverte; tu ejemplo pesa más que tus órdenes.",
  },
  {
    numero: 21,
    nombre: "La Mordedura Tajante",
    chino: "噬嗑",
    pinyin: "Shì Kè",
    lineas: [1, 0, 0, 1, 0, 1],
    trigramaInferior: "trueno",
    trigramaSuperior: "fuego",
    palabrasClave: ["decisión", "justicia", "obstáculo", "claridad"],
    juicio: "Morder con fuerza a través del obstáculo trae éxito. Es favorable aplicar la justicia con energía y claridad.",
    imagen: "Trueno y relámpago juntos: fuerza y luz. Como los antiguos, define con claridad las normas y aplica las consecuencias con firmeza.",
    significado: "Hay un obstáculo entre los dientes que impide que las cosas se junten: un malentendido, un abuso, una mentira. Hoy toca enfrentarlo de forma directa y decidida, sin rodeos ni crueldad. La claridad que acompaña a la energía hace justa la acción.",
    amor: "Un tema incómodo pide ser encarado de frente; evitarlo mantiene la distancia entre ambos.",
    trabajo: "Resuelve el problema que traba el avance con decisión y transparencia; las reglas claras protegen a todos.",
  },
  {
    numero: 22,
    nombre: "La Gracia",
    chino: "賁",
    pinyin: "Bì",
    lineas: [1, 0, 1, 0, 0, 1],
    trigramaInferior: "fuego",
    trigramaSuperior: "montana",
    palabrasClave: ["belleza", "forma", "sencillez", "apariencia"],
    juicio: "La gracia tiene éxito, pero solo en asuntos menores conviene emprender algo. La forma embellece, mas no reemplaza el contenido.",
    imagen: "El fuego ilumina el pie de la montaña. Dedícate a aclarar los asuntos cotidianos, pero no decidas cuestiones graves basándote solo en la apariencia.",
    significado: "Es un momento de belleza, encanto y buen gusto, en el que la forma importa. Disfruta y cuida los detalles estéticos, pero no confundas el brillo con la sustancia. Lo grande y decisivo necesitará algo más que una buena presentación.",
    amor: "El romanticismo y los gestos bellos alegran la relación; recuerda que la base es la sinceridad.",
    trabajo: "Pule la presentación y la imagen, pero no tomes decisiones de fondo guiado por apariencias.",
  },
  {
    numero: 23,
    nombre: "La Desintegración",
    chino: "剝",
    pinyin: "Bō",
    lineas: [0, 0, 0, 0, 0, 1],
    trigramaInferior: "tierra",
    trigramaSuperior: "montana",
    palabrasClave: ["desgaste", "quietud", "desprendimiento", "resistir"],
    juicio: "No es favorable ir a ninguna parte: la situación se desmorona por su propio peso y lo inferior avanza.",
    imagen: "La montaña descansa sobre la tierra que la erosiona. Quienes están arriba solo aseguran su posición siendo generosos con quienes están abajo.",
    significado: "Algo en tu vida se está desgastando y no puedes evitarlo con acción directa. Lo sensato es quedarte quieto, no invertir en lo que ya cae y conservar tus fuerzas. Todo desprendimiento deja una semilla para el próximo ciclo.",
    amor: "Si algo se deshace, no te aferres con desesperación; acepta el proceso y cuida de ti.",
    trabajo: "No es momento de arriesgar ni de iniciar; mantente firme, observa y protege lo esencial.",
  },
  {
    numero: 24,
    nombre: "El Retorno",
    chino: "復",
    pinyin: "Fù",
    lineas: [1, 0, 0, 0, 0, 0],
    trigramaInferior: "trueno",
    trigramaSuperior: "tierra",
    palabrasClave: ["renacimiento", "punto de giro", "regreso", "suavidad"],
    juicio: "El retorno tiene éxito: la luz regresa sin violencia, los amigos vuelven y el ciclo se completa al séptimo día. Es favorable tener a dónde ir.",
    imagen: "El trueno late dentro de la tierra en pleno solsticio. Como quien cierra los caminos en ese día, descansa y deja que la energía nueva se afiance sin apuros.",
    significado: "Después de un tiempo oscuro, algo vuelve a moverse en ti: una fuerza, una esperanza, un vínculo. Es un cambio delicado que no debe forzarse ni exponerse demasiado pronto. Regresa a lo que te hace bien y cuida el brote.",
    amor: "Un reencuentro o una segunda oportunidad es posible; avanza con ternura y sin apresurar.",
    trabajo: "Retoma un proyecto o camino que habías dejado; empieza en pequeño y con cuidado.",
  },
  {
    numero: 25,
    nombre: "La Inocencia",
    chino: "無妄",
    pinyin: "Wú Wàng",
    lineas: [1, 0, 0, 1, 1, 1],
    trigramaInferior: "trueno",
    trigramaSuperior: "cielo",
    palabrasClave: ["espontaneidad", "sinceridad", "naturalidad", "sin cálculo"],
    juicio: "Actuar sin segundas intenciones trae gran éxito y conviene perseverar. Quien se aparta de lo correcto atrae desgracia y no debe emprender nada.",
    imagen: "El trueno recorre el cielo y todo se despierta con naturalidad. Como los antiguos, alimenta a los seres según su tiempo, sin manipular el proceso.",
    significado: "Lo mejor que puedes hacer hoy es actuar desde tu verdad, sin calcular ventajas ni anticipar recompensas. Lo inesperado puede ocurrir, pero no te dañará si tu intención es limpia. Confía en tu instinto sano y no te enredes en estrategias.",
    amor: "Muéstrate tal como eres, sin juegos ni cálculos; la sinceridad es lo que enamora.",
    trabajo: "Haz tu trabajo con honestidad y sin maniobras; lo genuino da mejores frutos que lo astuto.",
  },
  {
    numero: 26,
    nombre: "La Fuerza Domesticadora de lo Grande",
    chino: "大畜",
    pinyin: "Dà Chù",
    lineas: [1, 1, 1, 0, 0, 1],
    trigramaInferior: "cielo",
    trigramaSuperior: "montana",
    palabrasClave: ["acumulación", "contención", "sabiduría", "gran empresa"],
    juicio: "Conviene perseverar y no quedarse en casa; cruzar grandes aguas es favorable. La fuerza acumulada con firmeza permite emprender grandes cosas.",
    imagen: "El cielo guardado dentro de la montaña. Estudia las palabras y hechos del pasado para fortalecer tu carácter.",
    significado: "Has acumulado energía, conocimiento y capacidad, y ahora esa fuerza pide un cauce mayor. Contener no es reprimir, sino dar forma a algo poderoso. Aprende de quienes vinieron antes y atrévete a un desafío importante.",
    amor: "Una intensidad contenida se transforma en compromiso firme si la conduces con madurez.",
    trabajo: "Es buen momento para asumir una responsabilidad grande; tu preparación te respalda.",
  },
  {
    numero: 27,
    nombre: "Las Comisuras de la Boca",
    chino: "頤",
    pinyin: "Yí",
    lineas: [1, 0, 0, 0, 0, 1],
    trigramaInferior: "trueno",
    trigramaSuperior: "montana",
    palabrasClave: ["nutrición", "alimento", "palabras", "cuidado"],
    juicio: "La nutrición correcta trae fortuna. Observa a quién alimentas y con qué te alimentas tú mismo.",
    imagen: "El trueno al pie de la montaña, como una boca que se abre. Sé cuidadoso con tus palabras y moderado con lo que comes.",
    significado: "El hexagrama te pregunta qué estás nutriendo en tu vida: qué consumes, qué dices y a quién dedicas tu cuidado. Lo que entra por la boca y lo que sale de ella definen tu bienestar. Elige alimento, ideas y compañías que te fortalezcan.",
    amor: "Cuida lo que dices y cómo lo dices; las palabras alimentan o envenenan el vínculo.",
    trabajo: "Alimenta tus habilidades y a tu equipo; evita comentarios imprudentes en el entorno laboral.",
  },
  {
    numero: 28,
    nombre: "La Preponderancia de lo Grande",
    chino: "大過",
    pinyin: "Dà Guò",
    lineas: [0, 1, 1, 1, 1, 0],
    trigramaInferior: "viento",
    trigramaSuperior: "lago",
    palabrasClave: ["sobrecarga", "crisis", "acción extraordinaria", "coraje"],
    juicio: "La viga maestra se dobla bajo el peso. Conviene tener a dónde ir y actuar con decisión: el momento exige medidas extraordinarias.",
    imagen: "El lago cubre los árboles. Sé capaz de mantenerte solo sin miedo y de retirarte del mundo sin amargura.",
    significado: "Estás cargando más de lo que la estructura puede sostener, y esperar solo agravará la tensión. Es tiempo de actuar con valentía y de tomar una decisión poco convencional. No lo hagas por impulso, sino con la calma de quien sabe que hay que moverse ya.",
    amor: "La relación soporta una presión excesiva; una conversación valiente puede aliviarla o transformarla.",
    trabajo: "La carga es insostenible; redistribuye, renuncia a algo o toma una decisión firme antes de que se quiebre.",
  },
  {
    numero: 29,
    nombre: "Lo Abismal",
    chino: "坎",
    pinyin: "Kǎn",
    lineas: [0, 1, 0, 0, 1, 0],
    trigramaInferior: "agua",
    trigramaSuperior: "agua",
    palabrasClave: ["peligro", "sinceridad", "profundidad", "constancia"],
    juicio: "El peligro se repite, pero si conservas la sinceridad interior el corazón sale adelante y la acción encuentra su sentido.",
    imagen: "El agua fluye sin cesar y llega a su destino sin detenerse en los pozos. Mantén tu virtud constante y repite las enseñanzas que te sostienen.",
    significado: "Atraviesas una zona de riesgo o de incertidumbre, quizá una tras otra. No puedes evitar el abismo, pero sí cruzarlo con la conducta del agua: sin apresurarte, llenando cada hueco antes de seguir. Tu integridad es la cuerda que te sostiene.",
    amor: "Hay una dificultad real en el vínculo; enfréntala con sinceridad y sin esconder lo que sientes.",
    trabajo: "Una etapa complicada exige constancia y honestidad; no busques atajos ni finjas que todo va bien.",
  },
  {
    numero: 30,
    nombre: "Lo Adherente",
    chino: "離",
    pinyin: "Lí",
    lineas: [1, 0, 1, 1, 0, 1],
    trigramaInferior: "fuego",
    trigramaSuperior: "fuego",
    palabrasClave: ["claridad", "luz", "dependencia", "lucidez"],
    juicio: "Perseverar es favorable y trae éxito. Cuidar de la vaca, lo dócil y nutricio, trae fortuna: la luz necesita algo a qué adherirse.",
    imagen: "El fuego brilla dos veces: la claridad se repite. Ilumina con esa luz las cuatro direcciones de tu vida.",
    significado: "Tu mente está clara y puedes ver con lucidez lo que antes era confuso. Recuerda que el fuego solo dura si tiene combustible: cuida aquello de lo que dependes. La calma y la docilidad mantendrán tu luz sin que te consuma.",
    amor: "Reconoce con claridad lo que te une a la otra persona y cultívalo con constancia.",
    trabajo: "Tu claridad mental es un recurso valioso; úsala para iluminar problemas sin quemar relaciones.",
  },
  {
    numero: 31,
    nombre: "El Influjo",
    chino: "咸",
    pinyin: "Xián",
    lineas: [0, 0, 1, 1, 1, 0],
    trigramaInferior: "montana",
    trigramaSuperior: "lago",
    palabrasClave: ["atracción", "cortejo", "sensibilidad", "receptividad"],
    juicio: "El influjo mutuo trae éxito y conviene perseverar. Tomar a una muchacha por esposa trae fortuna: la atracción sincera une.",
    imagen: "Un lago en la cima de la montaña. Mantén tu corazón vacío y receptivo para poder acoger a los demás.",
    significado: "Algo o alguien te atrae y esa atracción es recíproca. Deja que el influjo actúe sin intentar controlarlo ni acelerarlo. Estar disponible, sin ansiedad y con el corazón abierto, es lo que permite que la conexión florezca.",
    amor: "Una atracción genuina está en el aire; muéstrate receptivo y deja que la conexión se dé sola.",
    trabajo: "Escucha a colegas y clientes con apertura; la sensibilidad te hará más persuasivo que cualquier argumento.",
  },
  {
    numero: 32,
    nombre: "La Duración",
    chino: "恆",
    pinyin: "Héng",
    lineas: [0, 1, 1, 1, 0, 0],
    trigramaInferior: "viento",
    trigramaSuperior: "trueno",
    palabrasClave: ["constancia", "permanencia", "ritmo", "compromiso"],
    juicio: "La duración trae éxito y no hay error. Conviene perseverar y tener a dónde ir: lo duradero no es rigidez, sino un movimiento que se renueva.",
    imagen: "Trueno y viento se acompañan. Mantente firme en tu camino y no cambies de dirección con cada ventisca.",
    significado: "Lo que necesitas hoy es constancia, no novedades. Tu proyecto, tu vínculo o tu hábito piden un ritmo sostenido que los haga durar. Renueva tu compromiso sin buscar cambios bruscos.",
    amor: "La relación se fortalece con estabilidad y presencia diaria, no con sobresaltos.",
    trabajo: "Persevera en tu método y objetivos; la constancia es la que consolida resultados.",
  },
  {
    numero: 33,
    nombre: "La Retirada",
    chino: "遯",
    pinyin: "Dùn",
    lineas: [0, 0, 1, 1, 1, 1],
    trigramaInferior: "montana",
    trigramaSuperior: "cielo",
    palabrasClave: ["retirada", "dignidad", "estrategia", "distancia"],
    juicio: "La retirada trae éxito; en lo pequeño conviene perseverar. Retirarse a tiempo no es huir, sino conservar la fuerza.",
    imagen: "La montaña bajo el cielo: distante y serena. Mantén a la gente mezquina a distancia, sin odio, con dignidad.",
    significado: "Las fuerzas menores avanzan y hoy no vale la pena enfrentarlas de lleno. Retirarte de forma consciente y ordenada te protege y te da perspectiva. Elige bien el momento y hazlo con calma, no con rabia.",
    amor: "Tomar distancia por un tiempo puede ser lo más sano; hazlo con respeto y sin reproches.",
    trabajo: "Aléjate de conflictos o ambientes tóxicos con elegancia; conserva energía para lo que sí vale.",
  },
  {
    numero: 34,
    nombre: "El Poder de lo Grande",
    chino: "大壯",
    pinyin: "Dà Zhuàng",
    lineas: [1, 1, 1, 1, 0, 0],
    trigramaInferior: "cielo",
    trigramaSuperior: "trueno",
    palabrasClave: ["fuerza", "poder", "rectitud", "autocontrol"],
    juicio: "El gran poder es favorable si se mantiene dentro de lo correcto. La fuerza sin rectitud se vuelve brutalidad.",
    imagen: "El trueno retumba en lo alto del cielo. No des un solo paso que no esté de acuerdo con el orden correcto.",
    significado: "Tienes fuerza y la situación te permite usarla, pero justamente por eso debes vigilar tu conducta. El poder mal dirigido se convierte en atropello. Actúa con firmeza y sin excesos, y no confundas tener razón con tener derecho a todo.",
    amor: "Tu intensidad puede abrumar; usa tu fuerza para proteger y no para imponer.",
    trabajo: "Estás en una posición fuerte; ejércela con ética y respeto, no con prepotencia.",
  },
  {
    numero: 35,
    nombre: "El Progreso",
    chino: "晉",
    pinyin: "Jìn",
    lineas: [0, 0, 0, 1, 0, 1],
    trigramaInferior: "tierra",
    trigramaSuperior: "fuego",
    palabrasClave: ["avance", "reconocimiento", "claridad", "expansión"],
    juicio: "El progreso es como el príncipe que recibe muchos caballos y es recibido tres veces en un día: el avance viene acompañado de reconocimiento.",
    imagen: "El sol se eleva sobre la tierra. Haz brillar tu propia claridad y tu carácter.",
    significado: "Tu camino se abre y tu esfuerzo empieza a ser visto y valorado. Aprovecha esta luz creciente para avanzar con transparencia y sin ocultar tu talento. El progreso genuino ilumina también a quienes te rodean.",
    amor: "La relación avanza con claridad y calidez; deja que la otra persona vea quién eres.",
    trabajo: "El reconocimiento llega; avanza con visibilidad y comparte el mérito con tu equipo.",
  },
  {
    numero: 36,
    nombre: "El Oscurecimiento de la Luz",
    chino: "明夷",
    pinyin: "Míng Yí",
    lineas: [1, 0, 1, 0, 0, 0],
    trigramaInferior: "fuego",
    trigramaSuperior: "tierra",
    palabrasClave: ["adversidad", "discreción", "luz interior", "resistencia"],
    juicio: "En tiempos de oscuridad conviene perseverar en medio de la dificultad, protegiendo la propia luz sin exhibirla.",
    imagen: "La luz se ha hundido dentro de la tierra. Vive entre la gente velando tu brillo, y aun así mantente lúcido por dentro.",
    significado: "El entorno no favorece la verdad ni la claridad, y mostrar tu luz podría exponerte. No apagues tu integridad, pero cúbrela con prudencia. Hoy toca resistir con discreción y esperar a que amanezca.",
    amor: "No es momento de grandes confesiones; cuida tus sentimientos y observa antes de abrirte.",
    trabajo: "Mantén un perfil discreto en un ambiente hostil; protege tu integridad sin confrontar.",
  },
  {
    numero: 37,
    nombre: "La Familia",
    chino: "家人",
    pinyin: "Jiā Rén",
    lineas: [1, 0, 1, 0, 1, 1],
    trigramaInferior: "fuego",
    trigramaSuperior: "viento",
    palabrasClave: ["hogar", "roles", "afecto", "orden"],
    juicio: "La perseverancia de la mujer trae fortuna: cuando cada miembro de la familia cumple su lugar con amor, la casa se sostiene.",
    imagen: "El viento nace del fuego. Que tus palabras tengan sustancia y tu conducta constancia; así influyes desde dentro hacia afuera.",
    significado: "Lo que hoy importa está cerca: tu casa, tus vínculos íntimos, tu círculo más próximo. El orden y el cariño en ese núcleo se irradian al resto de tu vida. Cumple tu parte con lealtad y exige con dulzura.",
    amor: "La relación se construye en lo cotidiano: acuerdos claros, roles compartidos y afecto constante.",
    trabajo: "Cuida el clima de tu equipo como si fuera una familia; la coherencia entre lo que dices y haces es tu autoridad.",
  },
  {
    numero: 38,
    nombre: "El Antagonismo",
    chino: "睽",
    pinyin: "Kuí",
    lineas: [1, 1, 0, 1, 0, 1],
    trigramaInferior: "lago",
    trigramaSuperior: "fuego",
    palabrasClave: ["oposición", "diferencia", "malentendido", "pequeños logros"],
    juicio: "En medio de la oposición, solo los asuntos pequeños tienen éxito. No es momento para grandes acuerdos.",
    imagen: "Fuego arriba y lago abajo se mueven en direcciones opuestas. Conserva tu individualidad en medio de la comunidad.",
    significado: "Sientes distancia o desacuerdo con alguien, y las diferencias parecen insalvables. No intentes forzar una unidad total; busca puntos concretos y pequeños de encuentro. La diversidad también tiene su lugar y su valor.",
    amor: "Las diferencias se acentúan; no busques resolverlo todo hoy, sino un gesto pequeño de acercamiento.",
    trabajo: "Hay posiciones enfrentadas; concéntrate en acuerdos puntuales y respeta las diferencias de enfoque.",
  },
  {
    numero: 39,
    nombre: "El Impedimento",
    chino: "蹇",
    pinyin: "Jiǎn",
    lineas: [0, 0, 1, 0, 1, 0],
    trigramaInferior: "montana",
    trigramaSuperior: "agua",
    palabrasClave: ["obstáculo", "introspección", "ayuda", "rodeo"],
    juicio: "Conviene el suroeste y no el noreste; es favorable ver a la gran persona. Ante el impedimento, la perseverancia trae fortuna.",
    imagen: "Agua sobre la montaña: peligro por delante. Vuelve la mirada hacia ti y trabaja en tu propio carácter.",
    significado: "Hay un obstáculo real frente a ti y forzar el paso sería imprudente. La respuesta está en detenerte, revisar tu propia parte y buscar ayuda de alguien sabio. Tomar el camino más fácil, aunque sea más largo, es hoy la decisión inteligente.",
    amor: "Un bloqueo en la relación te invita a mirar tu parte antes de culpar al otro.",
    trabajo: "No embistas contra el problema; retrocede, pide consejo y busca otra ruta.",
  },
  {
    numero: 40,
    nombre: "La Liberación",
    chino: "解",
    pinyin: "Xiè",
    lineas: [0, 1, 0, 1, 0, 0],
    trigramaInferior: "agua",
    trigramaSuperior: "trueno",
    palabrasClave: ["alivio", "resolución", "perdón", "rapidez"],
    juicio: "Conviene el suroeste; si no queda nada por hacer, regresar trae fortuna, y si aún queda algo, apurarse es favorable.",
    imagen: "Trueno y lluvia disuelven la tensión acumulada. Perdona los errores y sé indulgente con las faltas.",
    significado: "La tensión que te oprimía empieza a disolverse, como el aire después de una tormenta. Resuelve lo pendiente con rapidez y luego vuelve a la normalidad sin demorarte en el drama. Perdonar, a otros y a ti mismo, forma parte de esta liberación.",
    amor: "Un conflicto se destraba; suelta rencores y no vuelvas a remover lo que ya pasó.",
    trabajo: "Se abre una salida a un problema; actúa pronto para cerrarlo y luego pasa página.",
  },
  {
    numero: 41,
    nombre: "La Merma",
    chino: "損",
    pinyin: "Sǔn",
    lineas: [1, 1, 0, 0, 0, 1],
    trigramaInferior: "lago",
    trigramaSuperior: "montana",
    palabrasClave: ["reducción", "sencillez", "sacrificio", "esencial"],
    juicio: "Mermar con sinceridad trae gran fortuna y no hay error. Aun con dos platos sencillos se puede hacer una ofrenda.",
    imagen: "El lago al pie de la montaña la desgasta. Controla tu ira y modera tus deseos.",
    significado: "Es tiempo de tener menos, gastar menos o ceder algo, y eso no es una pérdida sino una depuración. Lo que reduces por fuera fortalece lo de adentro. Simplifica, controla tus impulsos y da con lo que tengas, sin avergonzarte.",
    amor: "Renuncia a exigencias innecesarias; la sencillez y la sinceridad valen más que la abundancia.",
    trabajo: "Recorta gastos, tareas o pretensiones; concentrarte en lo esencial es una inversión.",
  },
  {
    numero: 42,
    nombre: "El Aumento",
    chino: "益",
    pinyin: "Yì",
    lineas: [1, 0, 0, 0, 1, 1],
    trigramaInferior: "trueno",
    trigramaSuperior: "viento",
    palabrasClave: ["crecimiento", "generosidad", "oportunidad", "acción"],
    juicio: "Es favorable emprender algo y cruzar grandes aguas: el aumento llega cuando lo de arriba se sacrifica por lo de abajo.",
    imagen: "Viento y trueno se potencian mutuamente. Cuando veas algo bueno, imítalo; cuando veas tus fallas, corrígelas.",
    significado: "Estás en una corriente de crecimiento y las circunstancias multiplican tus esfuerzos. Es el momento de actuar, emprender y arriesgar con sentido. Aprovecha la buena racha para mejorar también tu carácter.",
    amor: "El vínculo crece y se enriquece; sé generoso y disfruta de la abundancia compartida.",
    trabajo: "Las condiciones favorecen la expansión; da el paso que venías postergando.",
  },
  {
    numero: 43,
    nombre: "El Desbordamiento",
    chino: "夬",
    pinyin: "Guài",
    lineas: [1, 1, 1, 1, 1, 0],
    trigramaInferior: "cielo",
    trigramaSuperior: "lago",
    palabrasClave: ["decisión", "resolución", "verdad", "firmeza"],
    juicio: "Hay que denunciar la verdad con firmeza ante la corte, aun con peligro. Conviene avisar a los propios y no recurrir a las armas: emprender algo es favorable.",
    imagen: "El lago ha subido hasta el cielo y va a desbordarse. Reparte tus riquezas hacia abajo y evita apoyarte en tu propia virtud.",
    significado: "Algo debe decirse o decidirse con claridad, y ya no puedes postergarlo. Hazlo con firmeza pero sin agresión, exponiendo la verdad con transparencia. Cuídate de la arrogancia: la última resistencia cae sola si no la alimentas.",
    amor: "Es hora de hablar con franqueza sobre lo que te incomoda, con firmeza y sin ataque.",
    trabajo: "Toma la decisión pendiente y comunícala con claridad; una postura firme y honesta resuelve el impasse.",
  },
  {
    numero: 44,
    nombre: "El Ir al Encuentro",
    chino: "姤",
    pinyin: "Gòu",
    lineas: [0, 1, 1, 1, 1, 1],
    trigramaInferior: "viento",
    trigramaSuperior: "cielo",
    palabrasClave: ["encuentro", "tentación", "cautela", "influencia sutil"],
    juicio: "La muchacha es poderosa; no conviene desposarla. Lo que llega de forma inesperada y seductora puede crecer más de lo que parece.",
    imagen: "Bajo el cielo sopla el viento y alcanza cada rincón. Como el príncipe que difunde sus órdenes, comunica con claridad y a tiempo.",
    significado: "Algo pequeño y atractivo entra en tu vida, y aunque parece inofensivo puede tomar mucho espacio. Mantente alerta sin cerrarte: no todo encuentro es dañino, pero este pide discernimiento. Reconoce a tiempo lo que empieza a crecer.",
    amor: "Un encuentro seductor merece cautela; disfruta sin entregar todo antes de conocer bien a la persona.",
    trabajo: "Una propuesta tentadora puede tener letra pequeña; revisa bien antes de comprometerte.",
  },
  {
    numero: 45,
    nombre: "La Reunión",
    chino: "萃",
    pinyin: "Cuì",
    lineas: [0, 0, 0, 1, 1, 0],
    trigramaInferior: "tierra",
    trigramaSuperior: "lago",
    palabrasClave: ["congregación", "comunidad", "celebración", "previsión"],
    juicio: "La reunión tiene éxito cuando hay un centro y un líder digno de confianza. Es favorable hacer grandes ofrendas y emprender algo.",
    imagen: "El lago se recoge sobre la tierra. Renueva tus herramientas y prevé lo imprevisto, porque donde se junta mucha gente surgen también fricciones.",
    significado: "Se acerca un tiempo de reunirte con otros: familia, amigos, equipo o comunidad. La abundancia de esa reunión es real, pero conviene organizarla y anticipar tensiones. Aporta algo generoso y reconoce a quien la convoca.",
    amor: "Compartir espacios con la familia y los amigos de la otra persona fortalece el vínculo.",
    trabajo: "Reunir al equipo con un propósito claro da resultados; prepárate para gestionar desacuerdos.",
  },
  {
    numero: 46,
    nombre: "La Subida",
    chino: "升",
    pinyin: "Shēng",
    lineas: [0, 1, 1, 0, 0, 0],
    trigramaInferior: "viento",
    trigramaSuperior: "tierra",
    palabrasClave: ["ascenso", "esfuerzo", "crecimiento gradual", "confianza"],
    juicio: "La subida trae gran éxito; conviene ver a la gran persona y avanzar hacia el sur sin temor.",
    imagen: "El árbol crece dentro de la tierra, sin prisa y sin detenerse. Acumula lo pequeño para llegar a lo alto.",
    significado: "Estás ascendiendo, quizá sin notarlo, con el crecimiento silencioso de una planta. No hay saltos espectaculares, pero sí una dirección clara. Sigue con esfuerzo constante y busca el apoyo de quien pueda abrirte camino.",
    amor: "El vínculo crece de forma gradual y firme; valora cada pequeño paso.",
    trabajo: "Tu progreso es sostenido; persevera y acércate a quien pueda impulsarte.",
  },
  {
    numero: 47,
    nombre: "La Desazón",
    chino: "困",
    pinyin: "Kùn",
    lineas: [0, 1, 0, 1, 1, 0],
    trigramaInferior: "agua",
    trigramaSuperior: "lago",
    palabrasClave: ["agotamiento", "adversidad", "resistencia", "silencio"],
    juicio: "En el agotamiento, la persona íntegra persevera y encuentra éxito; pero cuando habla, nadie le cree. Es tiempo de hechos, no de palabras.",
    imagen: "El lago se ha quedado sin agua. Entrega tu vida a lo que consideras correcto, sin depender de que otros lo reconozcan.",
    significado: "Te sientes vaciado, presionado o incomprendido, y explicar tu situación no ayuda. La salida no está en convencer a nadie, sino en mantenerte fiel a ti mismo y resistir. Este agotamiento revela de qué estás hecho.",
    amor: "Las palabras hoy no llegan; demuestra con actos tu compromiso y cuida tu propia energía.",
    trabajo: "El desgaste es real y no te escuchan; concentra tus fuerzas en lo esencial y evita discusiones estériles.",
  },
  {
    numero: 48,
    nombre: "El Pozo",
    chino: "井",
    pinyin: "Jǐng",
    lineas: [0, 1, 1, 0, 1, 0],
    trigramaInferior: "viento",
    trigramaSuperior: "agua",
    palabrasClave: ["fuente", "profundidad", "servicio", "lo esencial"],
    juicio: "El pueblo cambia, pero el pozo permanece. Si la cuerda no llega al agua o el cántaro se rompe, hay desgracia: hay que ir hasta el fondo.",
    imagen: "El agua sube por la madera del pozo. Anima a las personas en su trabajo y ayúdalas a colaborar entre sí.",
    significado: "Hay una fuente profunda a tu disposición: tu vocación, tu sabiduría, un vínculo esencial. No basta con saber que existe, hay que bajar hasta ella con constancia y compartirla. Cuida el pozo y no dejes que se contamine ni se abandone.",
    amor: "El vínculo tiene una fuente profunda; vuelve a ella en vez de quedarte en la superficie.",
    trabajo: "Recurre a lo que verdaderamente sabes y ponlo al servicio de otros; lo esencial no se agota.",
  },
  {
    numero: 49,
    nombre: "La Revolución",
    chino: "革",
    pinyin: "Gé",
    lineas: [1, 0, 1, 1, 1, 0],
    trigramaInferior: "fuego",
    trigramaSuperior: "lago",
    palabrasClave: ["cambio", "transformación", "renovación", "momento justo"],
    juicio: "Cuando llega su día, la revolución encuentra confianza y gran éxito. El arrepentimiento desaparece si el cambio se hace con rectitud.",
    imagen: "Fuego en el lago: dos fuerzas que se combaten y transforman. Ordena el calendario y aclara los tiempos para que el cambio tenga sentido.",
    significado: "Algo en tu vida pide un cambio profundo, y ya no basta con parches. La transformación será exitosa si se hace en el momento oportuno y con intenciones claras que otros puedan comprender. Prepara el terreno y actúa cuando el día llegue.",
    amor: "La relación necesita una transformación real; propónla con claridad y en el momento adecuado.",
    trabajo: "Un cambio de rumbo es necesario; planéalo bien y comunica su sentido para que te acompañen.",
  },
  {
    numero: 50,
    nombre: "El Caldero",
    chino: "鼎",
    pinyin: "Dǐng",
    lineas: [0, 1, 1, 1, 0, 1],
    trigramaInferior: "viento",
    trigramaSuperior: "fuego",
    palabrasClave: ["nutrición", "cultura", "transformación", "ofrenda"],
    juicio: "El caldero trae gran fortuna y éxito: transforma lo crudo en alimento y lo alimenta todo con lo mejor.",
    imagen: "Fuego sobre la madera. Afirma tu posición con rectitud y así se cumplirá tu destino.",
    significado: "Tienes en tus manos algo capaz de transformar y nutrir: un talento, un proyecto, una vocación. Ofrécelo con dedicación y cuida la calidad de lo que produces. Lo que hoy cocines a fuego lento alimentará a muchos.",
    amor: "Nutre el vínculo con lo mejor de ti; la calidez y la dedicación lo transforman.",
    trabajo: "Refina tu oficio y ofrece un trabajo de calidad; tu posición se afirma por lo que aportas.",
  },
  {
    numero: 51,
    nombre: "Lo Suscitativo",
    chino: "震",
    pinyin: "Zhèn",
    lineas: [1, 0, 0, 1, 0, 0],
    trigramaInferior: "trueno",
    trigramaSuperior: "trueno",
    palabrasClave: ["conmoción", "despertar", "sobresalto", "serenidad"],
    juicio: "La conmoción trae éxito: llega el trueno y hay sobresalto, luego risa. Aunque aterre a todos, quien mantiene la calma no deja caer la cuchara del sacrificio.",
    imagen: "El trueno se repite y sacude todo. Con temor y respeto, examina tu vida y pon en orden lo que haga falta.",
    significado: "Algo te sacude de repente: una noticia, un susto, una revelación. El impacto es real, pero pasa, y lo que queda es la oportunidad de despertar. Mantén la serenidad en medio del temblor y revisa qué necesitas cambiar.",
    amor: "Una sorpresa o sacudida en la relación puede despertar algo dormido; no reacciones desde el miedo.",
    trabajo: "Un imprevisto altera los planes; conserva la calma y usa el sobresalto para revisar prioridades.",
  },
  {
    numero: 52,
    nombre: "El Aquietamiento",
    chino: "艮",
    pinyin: "Gèn",
    lineas: [0, 0, 1, 0, 0, 1],
    trigramaInferior: "montana",
    trigramaSuperior: "montana",
    palabrasClave: ["quietud", "meditación", "límite", "presencia"],
    juicio: "Aquietar la espalda hasta no sentir el cuerpo, caminar por el patio sin ver a nadie: en esa quietud no hay error.",
    imagen: "Dos montañas, una sobre otra. No dejes que tus pensamientos vayan más allá de la situación presente.",
    significado: "Hoy la sabiduría está en detenerte por completo, sin agitación ni planes. Aquietar el cuerpo y la mente te permite ver con claridad cuándo moverte de nuevo. Quédate en el presente y deja que lo demás espere.",
    amor: "Un tiempo de calma y silencio compartido hace más por la relación que cualquier conversación forzada.",
    trabajo: "Pausa antes de decidir; la quietud te mostrará el paso correcto cuando llegue el momento.",
  },
  {
    numero: 53,
    nombre: "La Evolución",
    chino: "漸",
    pinyin: "Jiàn",
    lineas: [0, 0, 1, 0, 1, 1],
    trigramaInferior: "montana",
    trigramaSuperior: "viento",
    palabrasClave: ["desarrollo gradual", "paciencia", "proceso", "compromiso"],
    juicio: "La evolución gradual trae fortuna, como la muchacha que es entregada en matrimonio con todos los pasos debidos. Conviene perseverar.",
    imagen: "Un árbol crece lentamente sobre la montaña. Cultiva tu dignidad y tu valor para mejorar también tu entorno.",
    significado: "Lo que buscas se logra por etapas, sin saltarse ninguna. Cada paso prepara el siguiente, como el ganso que avanza hacia la orilla, la roca y luego el árbol. Ten paciencia con el proceso y confía en el avance lento pero firme.",
    amor: "La relación madura paso a paso; respeta los tiempos y no exijas compromiso antes de tiempo.",
    trabajo: "Tu carrera avanza de forma gradual; cada logro pequeño sostiene el siguiente.",
  },
  {
    numero: 54,
    nombre: "La Muchacha que se Casa",
    chino: "歸妹",
    pinyin: "Guī Mèi",
    lineas: [1, 1, 0, 1, 0, 0],
    trigramaInferior: "lago",
    trigramaSuperior: "trueno",
    palabrasClave: ["posición subordinada", "tacto", "lo transitorio", "prudencia"],
    juicio: "Emprender algo trae desgracia: no hay nada que favorezca. La posición es delicada y las relaciones no están en igualdad.",
    imagen: "El trueno sobre el lago. Comprende lo pasajero a la luz de lo que perdura.",
    significado: "Entras en una situación en la que no tienes el control ni la posición más ventajosa. No es momento de exigir ni de iniciar, sino de moverte con tacto y de entender el largo plazo. Acepta tu lugar sin resignación y sin perder tu dignidad.",
    amor: "Una relación desigual o precipitada pide prudencia; no entregues más de lo que la situación permite.",
    trabajo: "Tu posición es secundaria por ahora; actúa con tacto y no fuerces reconocimiento.",
  },
  {
    numero: 55,
    nombre: "La Plenitud",
    chino: "豐",
    pinyin: "Fēng",
    lineas: [1, 0, 1, 1, 0, 0],
    trigramaInferior: "fuego",
    trigramaSuperior: "trueno",
    palabrasClave: ["abundancia", "cima", "claridad", "transitoriedad"],
    juicio: "La plenitud tiene éxito y el rey la alcanza. No te aflijas: sé como el sol al mediodía.",
    imagen: "Trueno y relámpago llegan juntos. Decide los pleitos y aplica las consecuencias con claridad y energía.",
    significado: "Estás en un punto alto de tu vida, con claridad y fuerza al mismo tiempo. Disfrútalo sin melancolía por lo que vendrá después: el mediodía es breve, pero es real. Usa esta luz para resolver lo que necesite justicia.",
    amor: "El vínculo vive un momento pleno; celébralo sin ansiedad por el futuro.",
    trabajo: "Estás en la cima de tu rendimiento; aprovecha la claridad para resolver asuntos pendientes.",
  },
  {
    numero: 56,
    nombre: "El Andariego",
    chino: "旅",
    pinyin: "Lǚ",
    lineas: [0, 0, 1, 1, 0, 1],
    trigramaInferior: "montana",
    trigramaSuperior: "fuego",
    palabrasClave: ["viaje", "transitoriedad", "prudencia", "adaptación"],
    juicio: "El andariego tiene éxito en lo pequeño; la perseverancia le trae fortuna. En tierra ajena conviene la modestia.",
    imagen: "Fuego sobre la montaña: arde y sigue su camino. Sé claro y prudente al juzgar, y no prolongues los pleitos.",
    significado: "Te sientes de paso, sin raíces firmes: un viaje, un cambio de lugar, una etapa provisoria. No pretendas conquistar el territorio; muévete con humildad, elige bien tus apoyos y no te enredes en conflictos. La ligereza es tu protección.",
    amor: "Una conexión pasajera o a distancia pide honestidad sobre lo que puedes ofrecer ahora.",
    trabajo: "En un entorno nuevo o provisional, observa las reglas del lugar y no busques imponerte.",
  },
  {
    numero: 57,
    nombre: "Lo Suave",
    chino: "巽",
    pinyin: "Xùn",
    lineas: [0, 1, 1, 0, 1, 1],
    trigramaInferior: "viento",
    trigramaSuperior: "viento",
    palabrasClave: ["penetración", "suavidad", "persistencia", "influencia"],
    juicio: "Lo suave tiene éxito en lo pequeño; conviene tener a dónde ir y ver a la gran persona. La influencia constante y sutil llega lejos.",
    imagen: "Viento que sigue al viento. Difunde tus intenciones con claridad y llévalas a cabo con constancia.",
    significado: "No lograrás lo que buscas con un golpe, sino con una influencia suave y repetida, como el viento que termina moldeando la roca. Ten una meta clara y vuelve a ella una y otra vez. Cuida que la suavidad no se convierta en indecisión.",
    amor: "La persuasión amable y sostenida acerca más que la insistencia; sé claro en lo que deseas.",
    trabajo: "Influye con constancia y sin estridencia; una idea bien repetida termina abriéndose paso.",
  },
  {
    numero: 58,
    nombre: "Lo Sereno",
    chino: "兌",
    pinyin: "Duì",
    lineas: [1, 1, 0, 1, 1, 0],
    trigramaInferior: "lago",
    trigramaSuperior: "lago",
    palabrasClave: ["alegría", "comunicación", "apertura", "amistad"],
    juicio: "La alegría serena tiene éxito y conviene perseverar. La verdadera alegría nace de la firmeza interior y la suavidad exterior.",
    imagen: "Dos lagos unidos que se alimentan uno al otro. Reúnete con amigos para conversar y aprender juntos.",
    significado: "El día invita a la alegría compartida, a la conversación y al intercambio abierto. Esa alegría es genuina cuando está sostenida por tu integridad, no por la adulación. Disfruta de la compañía y deja que el diálogo te enriquezca.",
    amor: "La alegría y el humor compartido fortalecen el vínculo; conversa con apertura.",
    trabajo: "Un ambiente de diálogo y buen ánimo hace fluir el trabajo; intercambia ideas con colegas.",
  },
  {
    numero: 59,
    nombre: "La Disolución",
    chino: "渙",
    pinyin: "Huàn",
    lineas: [0, 1, 0, 0, 1, 1],
    trigramaInferior: "agua",
    trigramaSuperior: "viento",
    palabrasClave: ["dispersión", "desbloqueo", "reunión", "apertura"],
    juicio: "La disolución tiene éxito: el rey acude al templo y es favorable cruzar grandes aguas. Lo que estaba rígido se disuelve y vuelve a fluir.",
    imagen: "El viento sopla sobre el agua y la dispersa. Como los antiguos reyes que ofrecían sacrificios y construían templos, reúne a la gente en torno a algo más grande que el egoísmo.",
    significado: "Algo que estaba bloqueado, endurecido o separado empieza a disolverse: rencores, aislamiento, rigidez. Deja que esa corriente se lleve lo que separa y te acerque a los demás. Es un buen momento para emprender y para reconectar.",
    amor: "La distancia y la frialdad se disuelven; da el primer paso hacia el reencuentro.",
    trabajo: "Se rompe un estancamiento; aprovecha para reunir al equipo en torno a un propósito común.",
  },
  {
    numero: 60,
    nombre: "La Limitación",
    chino: "節",
    pinyin: "Jié",
    lineas: [1, 1, 0, 0, 1, 0],
    trigramaInferior: "lago",
    trigramaSuperior: "agua",
    palabrasClave: ["límites", "medida", "disciplina", "equilibrio"],
    juicio: "La limitación tiene éxito, pero una limitación amarga no debe persistir. Los límites justos dan forma y libertad.",
    imagen: "Agua sobre el lago: el lago tiene una capacidad y el exceso se desborda. Establece medidas y reflexiona sobre lo que es correcto.",
    significado: "Hoy necesitas poner límites: al gasto, al tiempo, a las exigencias propias o ajenas. Los límites bien puestos no te encierran, te dan forma y te ahorran desgaste. Evita, eso sí, una severidad que se vuelva castigo.",
    amor: "Acordar límites claros y respetuosos protege el vínculo; no confundas límite con castigo.",
    trabajo: "Define alcances, horarios y presupuestos; la disciplina te dará más margen, no menos.",
  },
  {
    numero: 61,
    nombre: "La Verdad Interior",
    chino: "中孚",
    pinyin: "Zhōng Fú",
    lineas: [1, 1, 0, 0, 1, 1],
    trigramaInferior: "lago",
    trigramaSuperior: "viento",
    palabrasClave: ["sinceridad", "confianza", "empatía", "influencia"],
    juicio: "La verdad interior alcanza incluso a cerdos y peces: trae fortuna, permite cruzar grandes aguas y conviene perseverar.",
    imagen: "El viento sobre el lago: la superficie responde a lo invisible. Analiza los asuntos con comprensión y modera las penas.",
    significado: "Tu sinceridad es hoy tu mayor fuerza: cuando lo que dices coincide con lo que sientes, los demás lo perciben y confían. Esa confianza permite atravesar situaciones difíciles. Escucha con empatía y juzga con comprensión.",
    amor: "La conexión sincera y profunda es posible; muestra lo que hay en tu corazón sin máscaras.",
    trabajo: "La confianza que inspiras abre puertas; comunica desde la honestidad y escucha de verdad.",
  },
  {
    numero: 62,
    nombre: "La Preponderancia de lo Pequeño",
    chino: "小過",
    pinyin: "Xiǎo Guò",
    lineas: [0, 0, 1, 1, 0, 0],
    trigramaInferior: "montana",
    trigramaSuperior: "trueno",
    palabrasClave: ["cautela", "detalle", "humildad", "lo pequeño"],
    juicio: "Lo pequeño tiene éxito y conviene perseverar; se pueden hacer cosas pequeñas, no grandes. El pájaro que vuela no debe subir, sino bajar: así hay gran fortuna.",
    imagen: "Trueno sobre la montaña: un sonido cercano y contenido. En la conducta, exagera la reverencia; en el duelo, el pesar; en el gasto, la sobriedad.",
    significado: "No es momento de grandes vuelos ni ambiciones. Concéntrate en los detalles, en los gestos modestos y en cumplir con humildad lo cotidiano. Lo pequeño bien hecho es hoy tu mejor camino.",
    amor: "Los pequeños cuidados y la atención a los detalles dicen más que las promesas grandes.",
    trabajo: "Cumple con lo concreto y evita proyectos ambiciosos por ahora; la prudencia te protege.",
  },
  {
    numero: 63,
    nombre: "Después de la Consumación",
    chino: "既濟",
    pinyin: "Jì Jì",
    lineas: [1, 0, 1, 0, 1, 0],
    trigramaInferior: "fuego",
    trigramaSuperior: "agua",
    palabrasClave: ["culminación", "equilibrio", "vigilancia", "transición"],
    juicio: "Éxito en lo pequeño y conviene perseverar. Al principio hay fortuna, al final desorden: todo está en su lugar, pero ese orden es frágil.",
    imagen: "El agua sobre el fuego: cocina, pero si el equilibrio se rompe, se apaga o se evapora. Piensa en el peligro que sigue al logro y prevénlo.",
    significado: "Has logrado algo importante y las piezas encajan. Justo por eso, ahora es cuando más cuidado necesitas: el equilibrio perfecto tiende a desordenarse. Atiende los detalles, mantén lo conseguido y no te duermas en el éxito.",
    amor: "La relación está en armonía; cuídala con atención diaria para que no se desgaste.",
    trabajo: "El objetivo se cumplió; consolida y vigila los detalles para no perder lo ganado.",
  },
  {
    numero: 64,
    nombre: "Antes de la Consumación",
    chino: "未濟",
    pinyin: "Wèi Jì",
    lineas: [0, 1, 0, 1, 0, 1],
    trigramaInferior: "agua",
    trigramaSuperior: "fuego",
    palabrasClave: ["transición", "casi", "prudencia", "esperanza"],
    juicio: "Hay éxito, pero si el zorro joven moja la cola cuando casi ha cruzado el río, nada resulta favorable. La meta está cerca y exige más cuidado que nunca.",
    imagen: "El fuego sobre el agua: todavía no cooperan. Distingue con cuidado la naturaleza de las cosas para ponerlas en su lugar.",
    significado: "Estás a punto de terminar algo, pero aún no lo has logrado, y ese último tramo es el más delicado. No celebres antes de tiempo ni te descuides en la orilla. Con prudencia y atención, la transición se completa.",
    amor: "El vínculo está en transición hacia algo nuevo; no fuerces el cierre ni te apresures.",
    trabajo: "Falta el paso final y es el más importante; revisa todo antes de dar por terminado el proyecto.",
  },
];

/** Devuelve el hexagrama cuyo patrón de líneas coincide (de abajo hacia arriba). */
export function hexagramaPorLineas(lineas: readonly (0 | 1)[]): Hexagrama | undefined {
  const clave = lineas.join("");
  return HEXAGRAMAS.find((h) => h.lineas.join("") === clave);
}

/** Devuelve el hexagrama por su número en el orden del Rey Wen (1..64). */
export function hexagramaPorNumero(numero: number): Hexagrama | undefined {
  return HEXAGRAMAS[numero - 1];
}
